fan-maum/fanplus-front

src/api/Vote.ts
src/components/molecules/VoteListTab.tsx
src/components/organisms/VotePagination.tsx
src/pages/api/votes.ts
src/pages/votes.tsx

- serverSideProps 에러 핸들링 추가
- header navBar 추가

[develop] 에러핸들링, header navBar 추가

---

package.json
src/components/molecules/VoteListTab.tsx
src/components/molecules/VoteTitle.tsx
src/components/organisms/VoteListItem.tsx
src/components/organisms/VotePagination.tsx
src/components/templates/VoteLayout.tsx
src/hooks/useLanguage.ts
src/pages/_app.tsx
src/pages/api/votes.ts
src/pages/en/votes.tsx
src/pages/es/votes.tsx
src/pages/in/votes.tsx
src/pages/ja/votes.tsx
src/pages/vi/votes.tsx
src/pages/zh-rCN/votes.tsx
src/pages/zh-rTW/votes.tsx
src/store/voteLangState.ts
src/texts/en.ts
src/texts/es.ts
src/texts/in.ts
src/texts/ja.ts
src/texts/ko.ts
src/texts/vi.ts
src/texts/zh-rCN.ts
src/texts/zh-rTW.ts
src/types/vote.ts
src/utils/util.ts
yarn.lock

- 상단 탭 고정
- 투표 상세 페이지 연결
- 다국어 설정 (recoil atom => voteLangState.ts 참고)

[develop] feat: recoil atom으로 다국어설정

---

next.config.js
src/components/molecules/VoteListTab.tsx

- 지원하지 않는 페이지 => old.fanplus.co.kr로 redirect 시켜주는 로직 추가

[develop] feat: add rewrites fallback

---

src/components/layout/Footer.tsx
src/components/mainPage/MainPage.tsx
src/components/organisms/BusinessFormHandle.tsx

1. 중국어 선택시, 기존의 단어별 끊기 (word-break 속성값으로 keep-all) 로 인해 오버플로우 문제가 있었습니다.
keep-all  --> break-word 로 수정하였습니다.
2. business form api 호출 path를 env로 설정하였습니다.
3. footer 영역의 문의 메일 주소 변경하였습니다.
의도치 않게 스타일 수정 branch에서 작업한 점 양해부탁드립니다..

[develop] 스타일 및 form api 변경 등의 수정 사항

---

src/components/molecules/VoteListTab.tsx
src/styles/globals.css

PC 환경에서 VoteListTab의 윗부분이 NavBar에 가리는 문제 있어 수정하였습니다.
ios 환경에서 글자 깨짐 문제 있어 수정하였습니다.

[develop] VoteListTab 상단 짤림 문제(top 속성값 변경) 및 ios 글자깨짐 문제

---

src/components/templates/FAQTemplate.tsx

FAQContent.tsx 파일에 이미 존재하는 QuestionType이
FAQTemplate.tsx 파일에도 중복 선언되어 있어 삭제했습니다.

[develop] 수정: type 중복 선언 제거

---

src/components/atoms/RankProfile.tsx
src/components/molecules/voteDetail/VoteDetailPrizeBox.tsx
src/components/molecules/voteDetail/VoteStarState.tsx
src/components/organisms/VoteListItem.tsx
src/components/organisms/voteDetail/VoteDetailHeader.tsx
src/components/organisms/voteDetail/VoteDetailInfo.tsx
src/components/organisms/voteDetail/VoteDetailList.tsx
src/components/organisms/voteDetail/VoteDetailListItem.tsx
src/components/organisms/voteDetail/VoteDetailPrizeList.tsx
src/components/templates/VoteDetailLayout.tsx
src/hooks/useLanguage.ts
src/pages/en/voteDetail.tsx
src/pages/es/voteDetail.tsx
src/pages/in/voteDetail.tsx
src/pages/ja/voteDetail.tsx
src/pages/vi/voteDetail.tsx
src/pages/zh-rCN/voteDetail.tsx
src/pages/zh-rTW/voteDetail.tsx
src/store/voteLangState.ts
src/texts/en.ts
src/texts/es.ts
src/texts/in.ts
src/texts/ja.ts
src/texts/ko.ts
src/texts/vi.ts
src/texts/zh-rCN.ts
src/texts/zh-rTW.ts

[develop] 다국어 언어 스트링 추가

---

.eslintrc
package.json
src/components/molecules/VoteListTab.tsx
src/components/molecules/VoteTitle.tsx
src/components/molecules/voteDetail/VoteStarState.tsx
src/components/organisms/BusinessFormHandle.tsx
src/components/organisms/VoteListItem.tsx
src/components/organisms/VotePagination.tsx
src/components/organisms/voteDetail/VoteDetailHeader.tsx
src/components/organisms/voteDetail/VoteDetailInfo.tsx
src/components/organisms/voteDetail/VoteDetailItem.tsx
src/components/organisms/voteDetail/VoteDetailList.tsx
src/components/organisms/voteDetail/VoteDetailListItem.tsx
src/components/organisms/voteDetail/VoteDetailPrizeList.tsx
src/components/templates/VoteDetailLayout.tsx
src/components/templates/VoteLayout.tsx
src/hooks/useLanguage.ts
src/pages/api/voteDetail.ts
src/utils/util.ts
yarn.lock

- eslintrc no-console rules 추가

[develop] document: eslintrc no-console rules 추가

---

src/components/atoms/Chip.tsx
src/components/atoms/VoteModalButton.tsx
src/components/modals/CommonModal.tsx
src/components/modals/VoteBlockModal.tsx
src/components/modals/VoteDoneModal.tsx
src/components/modals/VoteProcessModal.tsx
src/components/molecules/VoteModalText.tsx
src/components/templates/VoteDetailLayout.tsx
src/styles/Colors.ts

- VoteProcessModal : 투표하시겠습니까?
- VoteDoneModal : 투표완료되었습니다.
- VoteBlockModal : 하루에 한 번 투표에 참여할 수 있어요.
VoteDetailLayout.tsx line 161 => function voteOnClick 내 setVoteModal, setVoteModalDone, setVoteModalBlock 참고

[develop] voteDetailPage => add vote modal

---

src/components/modals/CommonModal.tsx
src/components/modals/VoteBlockModal.tsx
src/components/modals/VoteDetailShareModal.tsx
src/components/modals/VoteDoneModal.tsx
src/components/modals/VoteProcessModal.tsx
src/components/molecules/VoteModalText.tsx
src/hooks/useCopyText.ts
src/hooks/useHtmlElement.ts
src/store/voteLangState.ts
src/styles/globals.css
src/texts/en.ts
src/texts/es.ts
src/texts/in.ts
src/texts/ja.ts
src/texts/ko.ts
src/texts/vi.ts
src/texts/zh-CN.ts
src/texts/zh-TW.ts
src/types/vote.ts

- vote title 내 date multi-language 변경
- Votemodal multi-language 작업

[develop] vote multi-language

---

src/components/atoms/Language.tsx
src/utils/setLangCookie.ts

라우팅 기능으로 인해 다른 언어를 선택해도 기존 언어가 유지되는 문제가 있어 수정했습니다.
배포전에 꼭 포함해야할 것 같습니다

[develop] fix: 언어선택해도 안 바뀌는 문제(Link -> button)

---

src/components/modals/VoteBlockModal.tsx
src/components/modals/VoteDoneModal.tsx
src/components/modals/VoteProcessModal.tsx
src/store/voteLangState.ts
src/texts/en.ts
src/texts/es.ts
src/texts/in.ts
src/texts/ja.ts
src/texts/ko.ts
src/texts/vi.ts
src/texts/zh-CN.ts
src/texts/zh-TW.ts

[develop] feat: add vote modal button multi-language

---

src/components/templates/VoteDetailLayout.tsx

로컬 서버에서 작동 하는 것까지 확인 되었습니다. (데스크톱 및 aos, ios 모두 확인 완료)
query문에 ofl 속성 추가 및 인코딩 범위 변경(link 쿼리문에만 인코딩) 통해 구현했습니다.

[develop] dynamic link 연결

---

src/components/atoms/RankProfile.tsx
src/components/molecules/VoteHighRankTab.tsx
src/components/molecules/VoteTitle.tsx
src/components/molecules/VoteTitleImage.tsx
src/components/organisms/VoteList.tsx
src/components/organisms/VoteListItem.tsx
src/components/organisms/voteDetail/VoteDetailInfo.tsx
src/components/organisms/voteDetail/VoteDetailItem.tsx
src/texts/en.ts
src/texts/es.ts
src/texts/in.ts
src/texts/ja.ts
src/texts/ko.ts
src/texts/vi.ts
src/texts/zh-CN.ts
src/texts/zh-TW.ts
src/types/vote.ts

투표 시작까지 ~ 기능 추가 및
투표 리스트 페이지에서 현재 1, 2등 차이 및 완료 투표의 우승자 표시하는 기능 추가

[develop] 투표 페이지 신규 기능

---

src/components/organisms/VoteListItem.tsx

모바일 환경에서 투표 사이에 구분선이 추가 되었습니다.
투표 아래 투표현황에 링크를 추가하였습니다.

[develop] 투표 페이지 기능 추가 2

---

src/components/organisms/voteDetail/VoteDetailInfo.tsx

1, 2위 투표 현황이 모바일 환경에서 너무 길게 표현되는 문제가 발생해 수정하였습니다.

[develop] 수정: 투표상세페이지에서 투표현황 비율 문제

---

src/components/modals/OtherBrowserModal.tsx
src/components/templates/LoginTemplate.tsx
src/texts/en.ts
src/texts/es.ts
src/texts/in.ts
src/texts/ja.ts
src/texts/ko.ts
src/texts/vi.ts
src/texts/zh-CN.ts
src/texts/zh-TW.ts
src/types/textTypes.ts

1. alert 대신 모달로 변경
2. 위챗, 라인, 페북, 인스타 인앱 브라우저 통한 로그인 차단 목록에 추가

[로그인기능] 구글로그인불가모달

---

src/components/modals/OtherBrowserModal.tsx
src/components/templates/LoginTemplate.tsx
src/texts/en.ts
src/texts/es.ts
src/texts/in.ts
src/texts/ja.ts
src/texts/ko.ts
src/texts/vi.ts
src/texts/zh-CN.ts
src/texts/zh-TW.ts
src/types/textTypes.ts

블락 처리가 모달로 뜨게 하였고,
네이버, 네이버 카페, 다음 앱, 카카오, 위챗, 라인, 인스타그램, 페북 등의 인앱 브라우저에서 구글 로그인 시 블락 처리됩니다.
ios, aos 등 다중 환경에서 작동 확인도 완료되었습니다.

[develop] google-login 블락 처리

---

src/components/atoms/LoginButtons/BaseLoginButton.tsx
src/components/templates/MainPageTemplate.tsx

1. mainpage에서 로그인, 회원가입 링크 없앴습니다.
2. ios에서 로그인창 접속시 폰트 색상이 푸른색으로 보이는 문제 해결

[develop] design 버그 제거

---

src/components/modals/OtherBrowserModal.tsx
src/components/templates/LoginTemplate.tsx

[develop] 로그인 불가 모달 텍스트 오류 수정

---

src/components/atoms/ShareButtonWithIcon.tsx
src/components/atoms/UnstyledButton.tsx
src/components/atoms/VoteModalButton.tsx
src/components/modals/CommonModal.tsx
src/components/modals/VoteBlockModal.tsx
src/components/modals/VoteDetailShareModal.tsx
src/components/modals/VoteDoneModal.tsx
src/components/modals/VoteProcessModal.tsx

투표하기 버튼, 앱 설치하기 버튼, 공유하기 버튼에 gtm 연동할 수 있도록 id 값 설정하였습니다.

[develop] Gtm연동

---

src/api/Community.ts
src/components/organisms/CommunityBoardWrapper.tsx
src/components/templates/CommunityBoardTemplate.tsx
src/components/templates/CommunityPageTemplate.tsx
src/hooks/useLanguage.ts
src/pages/api/community/board.ts
src/pages/ko/community/board.tsx
src/pages/ko/community/board/[boardIndex].tsx
src/pages/vi/community/board.tsx
src/pages/vi/community/board/[boardIndex].tsx
src/pages/zh-CN/community/board.tsx
src/pages/zh-CN/community/board/[boardIndex].tsx
src/types/common.ts
src/types/community.ts

[feat/community] 커뮤니티 게시판 기초 작업

---

src/pages/api/community/post.ts
src/pages/ko/community/board/[boardIndex]/[postIndex]/edit.tsx

비로그인 상태에서 api call을 했을 때 발생하는 error에 대한 handling을 다음과 같이 하는 게 맞는지 여쭤봅니당,,

[feat/community] error handling 

---

src/components/atoms/CommunityModalButton.tsx
src/components/atoms/NavBox.tsx
src/components/templates/CommunityBoardTemplate.tsx
src/editor/screen/FullEditor.tsx

1. 모달창 버튼 클릭시 버튼 색상 변경을 추가했습니다
2. qa3차 17번 상단 탑 네비 간격 이슈

[feat/community] qa3차 추가사항

---

src/components/organisms/community/PostCommentWrapper.tsx
src/components/templates/CommunityPostTemplate.tsx
src/server/useGetCommentsQuery.ts
src/store/community.ts

fix: edit updating comments logic - QA 3rd

---

src/components/templates/VoteDetailLayout.tsx
src/pages/api/vote.ts

에러 발생시 alert 기능을 이용해 api 의 response로 내려오는 메시지를 보여줍니다.

[master] vote api의 error handling 실서버 배포

---

src/components/modals/CommonModal.tsx
src/components/modals/VoteEndModal.tsx
src/components/templates/VoteDetailLayout.tsx
src/texts/en.ts
src/texts/es.ts
src/texts/in.ts
src/texts/ja.ts
src/texts/ko.ts
src/texts/vi.ts
src/texts/zh-CN.ts
src/texts/zh-TW.ts

Notion: https://www.notion.so/web-6beee8d4cb47405dbde58df79d418339

[master] 마감된 투표는 투표 종료 모달을 띄웁니다

---

src/components/molecules/community/PostDetailCopyUrl.tsx
src/pages/api/community/post.ts

1. 링크 href 오류
2. 색상 변경
3. 게시글 조회수 안 올라가는 이슈 해결

[develop] 게시글 주소 복사 관련 qa 

---

src/api/Community.ts
src/components/atoms/IconArrowDown.tsx
src/components/atoms/IconDecreased.tsx
src/components/atoms/IconHyphen.tsx
src/components/atoms/IconIncreased.tsx
src/components/molecules/community/PopularBoardItem.tsx
src/components/molecules/community/PopularBoardRightItems.tsx
src/components/molecules/community/PopularBoards.tsx
src/components/molecules/community/PopularBoardsMobile.tsx
src/components/templates/CommunityBoardTemplate.tsx
src/components/templates/CommunityLayout.tsx
src/components/templates/CommunityMyPostTemplate.tsx
src/components/templates/CommunityPageTemplate.tsx
src/components/templates/CommunityPostTemplate.tsx
src/pages/api/community/PopularTop30.ts
src/texts/communityLayoutTexts.ts
src/types/community.ts
src/types/textTypes.ts

api가 아직 안 나와있어서 api 연결 부분만 남아있습니다
api 연결 이후 값에 따라 map 함수 쓸 예정이라 현재 PopularBoardItem는 임시 dummy 값입니당

[develop] 인기 게시판 TOP 30 작업

---

package.json
src/server/useGetPopularBoardsQuery.ts
src/texts/communityLayoutTexts.ts

[develop] Top30 Qa

---

src/components/molecules/community/CommentInfoState.tsx
src/components/molecules/community/CommunityBoardArticle.tsx
src/components/molecules/community/CommunityPostInfoState.tsx
src/utils/communityUtil.ts
src/utils/util.ts

1. 신규 기획에 맞게 함수를 수정
2. 리팩토링 - 사용하지 않는 시간 함수 제거

[feat/community] 게시글, 댓글 등 작성시각 로직 변경

---

src/api/Community.ts
src/components/molecules/community/CommunityBoardArticle.tsx
src/components/organisms/community/CommunityBoardArticleTable.tsx
src/components/templates/CommunityBoardTemplate.tsx
src/pages/[locale]/community/board/[boardIndex]/index.tsx
src/pages/[locale]/community/board/[boardIndex]/mypost.tsx
src/pages/api/community/board.ts
src/types/community.ts

[feat/community-hj] 상세 게시판 게시글 리스트 상단 공지 작업 및 api 변경

---

src/components/atoms/IconArrowDown.tsx
src/components/molecules/community/CommunityBoardTopNavi.tsx
src/components/molecules/community/PopularBoardItem.tsx
src/components/molecules/community/PopularBoards.tsx
src/components/molecules/community/PopularBoardsMobile.tsx
src/components/molecules/community/PopularBoardsRolling.tsx
src/components/molecules/community/mobile/BoardMobileTitle.tsx
src/components/organisms/community/CommunityBoardSearchInputWrapper.tsx
src/components/templates/CommunityMainLayout.tsx
src/components/templates/CommunityMyPostTemplate.tsx
src/components/templates/CommunityPageTemplate.tsx
src/components/templates/PostEditorTemplate.tsx
src/pages/[locale]/community/index.tsx

- 게시판 타이틀 로직 <BoardMobileTitle> 하나로 통일
- TOP50 스타일 레이아웃 수정
- HOME 화면 : 전체글/BEST인기글 레이아웃 => 전체글 단일게시판 노출로 변경

[feat/community-mobile] 메인레이아웃 및 HOME 화면 CSS 수정

---

src/api/Community.ts
src/components/atoms/MobileWriteButton.tsx
src/components/atoms/WriteButton.tsx
src/components/molecules/community/CommunityBoardLangSelector.tsx
src/components/molecules/community/CommunityBoardTopNavi.tsx
src/components/molecules/community/mobile/BoardMobileDomainItem.tsx
src/components/molecules/community/mobile/BoardMobileTitle.tsx
src/components/organisms/community/BoardDomains.tsx
src/components/organisms/community/DomainTopicContainer.tsx
src/components/organisms/community/mobile/BoardMobileDomains.tsx
src/components/organisms/community/mobile/BoardMobileTab.tsx
src/components/templates/CommunityBoardLayout.tsx
src/components/templates/CommunityMainLayout.tsx
src/hooks/useBookmarkOnClick.ts
src/pages/[locale]/community/board/[boardIndex]/[postIndex]/edit.tsx
src/pages/[locale]/community/board/[boardIndex]/[postIndex]/index.tsx
src/pages/[locale]/community/board/[boardIndex]/index.tsx
src/pages/[locale]/community/board/[boardIndex]/write.tsx
src/pages/[locale]/community/bookmark.tsx
src/pages/[locale]/community/index.tsx
src/pages/[locale]/community/myPost.tsx
src/pages/[locale]/community/search.tsx
src/pages/api/community/multiBoardsInquiry.ts
src/server/query.ts
src/store/community.ts
src/texts/communityBoardTexts.ts
src/types/community.ts
src/types/textTypes.ts
src/utils/communityUtil.ts

- 게시판 제목 + 토픽 + 언어필터 보여주는 탭바 => BoardMobileTab component로 보여줌
- BoardMobileDomains => 어떤 게시판인지에 따라 routing 분기처리
- 글쓰기 버튼 - 플로팅 버튼 변경

[feat/community-mobile] topic bar - mobile

---

src/components/organisms/Layout.tsx
src/components/templates/CommunityMainLayout.tsx
src/pages/[locale]/business.tsx
src/pages/[locale]/faq.tsx
src/pages/[locale]/index.tsx
src/pages/[locale]/login.tsx
src/pages/[locale]/signUp.tsx
src/pages/[locale]/voteDetail.tsx
src/pages/_app.tsx

- 앱 내 웹뷰 확인을 위한 isWebview라는 변수 추가
- 동일된 Layout component => .app.tsx로 이동시켜 반복되는 로직 줄임.

[master] headers.isWebView 추가 및 Layout component => _app.tsx 로 변경

---

src/components/molecules/community/CommentInfoState.tsx
src/components/organisms/community/DomainTopicContainer.tsx
src/components/organisms/community/mobile/BoardMobileDomains.tsx
src/components/organisms/community/mobile/BoardMobileTab.tsx
src/components/templates/CommunityBookmarkTemplate.tsx
src/texts/communityBoardTexts.ts

1. BEST 인기글 (실시간) 상세게시판 토픽 삭제
2. 즐겨찾기 페이지 전체글, BEST 인기글(실시간) 게시판명 노출하도록 수정
4. 전체글에서 공지 게시글 클릭했을 때 오류 수정
5. BEST 인기글(실시간) 에서 공지 게시글 클릭했을 때 오류 수정
10. 차단이 해제되었습니다. 스트링 미적용 수정

[community-mobile] community mobile-QA 1,2,4,5,10번

---

src/components/atoms/OpenSideBardButton.tsx
src/components/atoms/PostToBoardButton.tsx
src/components/modals/CommunityBlockUserCommonModal.tsx
src/components/modals/CommunityBlockUserModal.tsx
src/components/molecules/community/NoBookMarkMessage.tsx
src/components/organisms/community/CommunityBoardArticleTable.tsx
src/components/organisms/community/CommunityBoardNoPost.tsx
src/components/organisms/community/mobile/BookmarkArticleTable.tsx
src/components/templates/CommunityBookmarkTemplate.tsx
src/texts/bookmarkTexts.ts
src/types/textTypes.ts

- 3) 즐겨찾기한 게시판이 없거나 비로그인 상태일 때 즐겨찾기 화면 수정
- 6) 전체글, BEST 인기글 게시판 제외 상세게시글에서 게시판명 노출 삭제
- 7) 게시글 없을 경우 글쓰기 버튼 오류 수정
- 8) 전체글, BEST 인기글(실시간) 차단할 경우 게시판 이동 수정
- 9) 일본어일 경우 차단하기 팝업창 취소 버튼 오류 수정

[community-mobile] mobile QA - 3,6,7,8,9번

---

src/components/molecules/community/mobile/MyPostTabBar.tsx
src/components/organisms/community/BoardDomains.tsx
src/components/organisms/community/DomainTopicContainer.tsx
src/components/organisms/community/mobile/BoardMobileDomains.tsx
src/components/templates/CommunityMyPostTemplate.tsx

router.push가 아닌 router.replace로 되어 있어 history가 제대로 동작하지 않았음.
router.replace => router.push 로 변경

[master] router.push / back 동작 오류 수정

---

src/components/modals/CommunityBlockUserModal.tsx
src/components/molecules/community/CommentPopover.tsx
src/components/molecules/community/mobile/BoardMobileDomainItem.tsx
src/components/organisms/community/CommentCard.tsx
src/components/organisms/community/PostCommentListItem.tsx
src/components/organisms/community/mobile/BoardMobileDomains.tsx

1. 답글이 있는 댓글 차단 시 답글도 노출 안 됨
2. 인도네시아어, 베트남어 선택 시 게시판 탭 벗어남

[master] 커뮤니티 QA

---

package.json
src/components/molecules/community/CommunityBoardArticleMobile.tsx
src/utils/util.ts
yarn.lock

[master] formatWrittenTimeLite 로직 변경
